//Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

//Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

//Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//Check Sessions
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

//공급사 엑셀 양식 리스트
export const SUPPLIER_FORM_LIST = "SUPPLIER_FORM_LIST";
export const SUPPLIER_FORM_LIST_SUCCESS = "SUPPLIER_FORM_LIST_SUCCESS";
export const SUPPLIER_FORM_LIST_FAILURE = "SUPPLIER_FORM_LIST_FAILURE";

//공급사 엑셀 양식 컬럼 상태값
export const SUPPLIER_FORM_COLUMN_STATUS = "SUPPLIER_FORM_COLUMN_STATUS";

//공급사 엑셀 양식 컬럼 기준정보 가져오기
export const SUPPLIER_FORM_COLUMN_INFO = "SUPPLIER_FORM_COLUMN_INFO";
export const SUPPLIER_FORM_COLUMN_INFO_SUCCESS = "SUPPLIER_FORM_COLUMN_INFO_SUCCESS";
export const SUPPLIER_FORM_COLUMN_INFO_FAILURE = "SUPPLIER_FORM_COLUMN_INFO_FAILURE";
