//Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

//Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

//Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//Check Sessions
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

//공급사 엑셀 양식 리스트
export const SUPPLIER_FORM_LIST = "SUPPLIER_FORM_LIST";
export const SUPPLIER_FORM_LIST_SUCCESS = "SUPPLIER_FORM_LIST_SUCCESS";
export const SUPPLIER_FORM_LIST_FAILURE = "SUPPLIER_FORM_LIST_FAILURE";

//공급사 엑셀 양식 추가
export const SUPPLIER_FORM_LIST_CREATE = "SUPPLIER_FORM_LIST_CREATE";
export const SUPPLIER_FORM_LIST_CREATE_SUCCESS = "SUPPLIER_FORM_LIST_CREATE_SUCCESS";
export const SUPPLIER_FORM_LIST_CREATE_FAILURE = "SUPPLIER_FORM_LIST_CREATE_FAILURE"

//공급사 엑셀 양식 수정
export const SUPPLIER_FORM_LIST_UPDATE = "SUPPLIER_FORM_LIST_UPDATE";
export const SUPPLIER_FORM_LIST_UPDATE_SUCCESS = "SUPPLIER_FORM_LIST_UPDATE_SUCCESS";
export const SUPPLIER_FORM_LIST_UPDATE_FAILURE = "SUPPLIER_FORM_LIST_UPDATE_FAILURE";

//공급사 엑셀 양식 삭제
export const SUPPLIER_FORM_LIST_DELETE = "SUPPLIER_FORM_LIST_DELETE";
export const SUPPLIER_FORM_LIST_DELETE_SUCCESS = "SUPPLIER_FORM_LIST_DELETE_SUCCESS";
export const SUPPLIER_FORM_LIST_DELETE_FAILURE = "SUPPLIER_FORM_LIST_DELETE_FAILURE";

//공급사 엑셀 양식 헤더 리스트 변경
export const SUPPLIER_FORM_LIST_COLUMN_INSERT = "SUPPLIER_FORM_LIST_COLUMN_INSERT";
export const SUPPLIER_FORM_LIST_COLUMN_INSERT_SUCCESS = "SUPPLIER_FORM_LIST_COLUMN_INSERT_SUCCESS";
export const SUPPLIER_FORM_LIST_COLUMN_INSERT_FAILURE = "SUPPLIER_FORM_LIST_COLUMN_INSERT_FAILURE";

//공급사 엑셀 양식 컬럼 상태값
export const SUPPLIER_FORM_COLUMN_STATUS = "SUPPLIER_FORM_COLUMN_STATUS";
